nanban: 
  name: Nanban
  username: 'Nanban#3270'
  client_id: '1406218928828448788'
  default_prefix: 'n!!'
  default_color: 0xD7D7D7
  extensions:
    - 'cogs.general'
    - 'cogs.nanban.utilities'
    - 'cogs.nanban.moderation'
    - 'cogs.nanban.voice'
    - 'cogs.nanban.radio'
    - 'cogs.nanban.thirukkural'
    - 'cogs.nanban.cosmic_con'
    - 'cogs.manage'